### ISSUE TITLE
Check immediate caller in `WithdrawBalance`

### ISSUE THREAD

**Issue by schomatis** [filecoin-project/specs-actors#662] opened 2020-07-14 02:12 UTC
https://github.com/filecoin-project/specs-actors/blob/f455e7ba8779f891dea089dcf5aa21bcb91a2420/actors/builtin/market/market_actor.go#L75-L80

`escrowAddress` will only check it if the caller is a `StorageMinerActorCodeID`, but otherwise will enforce only that `CallerTypesSignable`.

https://github.com/filecoin-project/specs-actors/blob/f455e7ba8779f891dea089dcf5aa21bcb91a2420/actors/builtin/market/market_actor.go#L776-L786

**Comment by anorth** [comment] 2020-07-14 04:28
Thanks, duplicate of #602.

**Closed by anorth** 2020-07-14 04:28 UTC
