### ISSUE TITLE
Restrict AddLockedFund method to reward actor

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs-actors#873] opened 2020-08-02 23:04 UTC
When a miner's initial pledge was locked in the vesting table, it was necessary for the miner operator to be able to lock up new funds to cover their initial pledge requirement. Now that IP doesn't vest, there's no reason for any call to AddLockedFund except by the reward actor distributing rewards.

Change caller validation to prevent this method being invoked by any other actor.

FYI @zixuanzh

**Comment by wadeAlexC** [comment] 2020-08-18 18:52
@anorth If you're open to it, I'd recommend moving this to P1; I'd like to be able to consider this the intended behavior.

A lot of my thinking at the moment revolves around reducing reliance on the cron actor, and one idea I've been exploring is miners tampering with the size of the vesting table via `AddLockedFund`.

Since `AddLockedFund` implicitly vests funds, there's a DOS vector if a miner can reliably force `handleProvingDeadline` to exit early (which may become easier if short-circuiting is implemented via #983). They can then stuff the vesting table via `AddLockedFund` with the goal of creating an unprocessable tipset at a far later date (due to the amount of vesting funds the block reward would end up unlocking).

**Comment by Stebalien** [comment] 2020-08-18 19:26
I assume we'd unlock funds every deadline, regardless of https://github.com/filecoin-project/specs-actors/issues/983.

**Comment by anorth** [comment] 2020-08-19 22:54
Let's do this anyway, thanks @wadeAlexC .

**Closed** 2020-09-01 05:47 UTC
Labels: P1, good first issue, robustness
