### ISSUE TITLE
Bounds usage of WPoStPeriodDeadlines may be inconsistent

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs-actors#792] opened 2020-07-24 10:03 UTC
Hello here, as part of the params audit @lucaniz and I found that at times we check that the deadline index is `> WPoStPeriodDeadlines` at times that it is `>= WPoStPeriodDeadlines`.

Is this intended

- [SubmitWindowedPoSt `>`](https://github.com/filecoin-project/specs-actors/blob/param-audit/actors/builtin/miner/miner_actor.go#L252)
- [PreCommitSector `>=`](https://github.com/filecoin-project/specs-actors/blob/param-audit/actors/builtin/miner/miner_actor.go#L453)
- [ExtendSectorExpiration `>=`](https://github.com/filecoin-project/specs-actors/blob/param-audit/actors/builtin/miner/miner_actor.go#L798)
- [TerminateSectors `>=`](https://github.com/filecoin-project/specs-actors/blob/param-audit/actors/builtin/miner/miner_actor.go#L953)
- [DeclareFaults `>=`](https://github.com/filecoin-project/specs-actors/blob/param-audit/actors/builtin/miner/miner_actor.go#L1072)
- [DeclareFaultsRecovered `>=`](https://github.com/filecoin-project/specs-actors/blob/param-audit/actors/builtin/miner/miner_actor.go#L1227)
- [CompactPartitions `>=`](https://github.com/filecoin-project/specs-actors/blob/param-audit/actors/builtin/miner/miner_actor.go#L1334)
- [declarationDeadlineInfo `>=`](https://github.com/filecoin-project/specs-actors/blob/param-audit/actors/builtin/miner/miner_actor.go#L2313)
- [NewDeadlineInfo `>`](https://github.com/filecoin-project/specs-actors/blob/param-audit/actors/builtin/miner/deadlines.go#L83)
- [SectorStatus `>=`](https://github.com/filecoin-project/specs-actors/blob/param-audit/actors/builtin/miner/miner_state.go#L721)

It seems that the only incorrect one is SubmitWindowedPoSt.

**Comment by anorth** [comment] 2020-07-24 13:00
`NewDeadlineInfo` uses `<`, rather than `>`, so is semantically equivalent to `>=` but in inverted sense.

The `SubmitWindowPoSt` one is duplicate of #753. Thanks for the diligence!

**Closed by anorth** 2020-07-24 13:00 UTC
