### ISSUE TITLE
Initial Pledge for Genesis Miners

### ISSUE THREAD

**Issue by zixuanzh** [filecoin-project/specs-actors#893] opened 2020-08-04 23:09 UTC
Total initial pledge at genesis should be computed from the same initial pledge calculation with genesis state, using initial values for alpha-beta filters. It is then divided pro rata based on Quality Adjusted power for each sector. Initial pledge for each genesis miner will be the sum of IPs for all their sectors.

**Comment by anorth** [comment] 2020-08-05 02:56
Duplicate of #707

**Closed by anorth** 2020-08-05 02:56 UTC
