### ISSUE TITLE
Only allow the reward actor to call AddLockedFunds

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/specs-actors#1055] opened 2020-08-28 17:53 UTC
Now that we never vest IP, there's no reason (as far as I know) for a miner to call AddLockedFunds (unless they just want to lock up money for some reason). We shouldn't allow miners to call this function.

**Comment by anorth** [comment] 2020-08-31 00:14
Duplicate of #873.

**Closed by anorth** 2020-08-31 00:14 UTC
Labels: P2, enhancement
