### ISSUE TITLE
Potential incorrect calculation of BR in `PledgePenaltyForTermination`

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs-actors#777] opened 2020-07-23 12:17 UTC
@lucaniz found a possible issue in this code:

https://github.com/filecoin-project/specs-actors/blob/master/actors/builtin/miner/monies.go#L57-L69

The function `PledgePenaltyForTermination` is meant to derive the BR from InitialPledge: ` BR(StartEpoch)=IP/InitialPledgeFactor`. This calculation should be done with `IPbase` instead.

Given the recent changes, we were not able to determine if initialPledge passed here is ipBase or IP.

**Comment by lucaniz** [comment] 2020-07-23 14:58
Our understanding is that 

`PledgePenaltyForTermination = Max ( PledgePenaltyForUndeclaredFault, ComputedTF)`

Where 

`ComputedTF = InitialPledgeForPower  + BR(StartEpoch)*min(SectorAgeInDays, 180))`
` =  InitialPledgeForPower  + (ipBase/20)*min(SectorAgeInDays, 180)) `

**Comment by ZenGround0** [comment] 2020-07-23 16:53
Pretty sure this is a duplicate of #701 if you disagree please reopen.

**Closed by ZenGround0** 2020-07-23 16:53 UTC
