### ISSUE TITLE
Miner: Don't request deal weight for empty deal array

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#904] opened 2020-08-05 19:35 UTC
`Miner.PreCommitSector` makes an unnecessary call to the Market actor when precommitting a CC Sector:

https://github.com/filecoin-project/specs-actors/blob/9d42fb163883f31325b08752c9f4e85d0b3ef22f/actors/builtin/miner/miner_actor.go#L1933-L1944

#### Recommendation

`requestDealWeight` should not invoke the market actor if `len(dealIDs) == 0`

**Comment by anorth** [comment] 2020-08-13 04:08
Closing as duplicate of #474, even though it's only part of it.

**Closed by anorth** 2020-08-13 04:08 UTC
Labels: P2, cleanup, scale
