### ISSUE TITLE
RepayDebtsOrAbort does not follow the "take fee from locked funds first" principle

### ISSUE THREAD

**Issue by irenegia** [filecoin-project/specs-actors#1283] opened 2020-10-27 13:51 UTC
To pay consensus of storage fault fees, we take money from LockedFunds first (and then from the available balance). See the method RepayPartialDebtInPriorityOrder.

It seems that the method RepayDebtsOrAbort does not respect this principle because it only consider the available balance (there is a call to getUnlockedBalance, but no call to UnlockUnvestedFunds).

RepayDebtsOrAbort does not follow the "first from locked funds" principle we have for fee.

**Comment by ZenGround0** [comment] 2020-10-27 17:41
Duplicate of #1282

**Closed by ZenGround0** 2020-10-27 17:41 UTC
