### ISSUE TITLE
BalanceTable MustSubtract changes state on error

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#652] opened 2020-07-13 14:07 UTC
The `MustSubtract` method of the adt `BalanceTable` persists a subtraction of all funds for the `key` argument in the case that not enough funds are subtracted and an error is thrown.  Do we expect this error penalization behavior?  Does it not matter because we always expect to be aborting from a state machine call and throwing out this state anyway when we hit this error case?

**Comment by aarshkshah1992** [comment] 2020-07-13 14:31
@ZenGround0 Thanks for raising this. I had this questions but forgot to file it. 
My suspicion is that we are relying on the "rollback" behaviour of the Runtime State.

**Comment by anorth** [comment] 2020-07-14 00:33
See #300. It's not great, but widespread.

**Comment by anorth** [comment] 2020-07-23 03:59
Closing as duplicate of #300

**Closed by anorth** 2020-07-23 03:59 UTC
Labels: P2, discussion, info-requested
