### ISSUE TITLE
Should parameters be in the state tree instead of in the code?

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs-actors#720] opened 2020-07-20 14:34 UTC
Hey there, I am having a concern understanding the design decision of storing the Filecoin parameters in the code rather than in the state.

Concern with storing in the code: If we want to change a param, it will change for all previous blocks. I expect majority of param changes to be changes from the "upgrade" block onwards. Without storing params on the state, we may end up writing nasty "if conditions" of the kind "if blockEpoch < blockChangeHappened: Use param X, otherwise: Use param Y".

Changing parameters for all previous states will be a very risky since we need to make sure that they are backward compatible with all the rest of the system (adding extra if conditions). Instead, if the parameters are in the state, we can always read what the parameters were back in the past and use those.

**Comment by ZenGround0** [comment] 2020-07-20 15:12
Thanks for raising this.  You are proposing a specific approach for the well understood but deprioritized objective "Actors as a whole are upgradeable, preserving complete validation compatibility with existing chain state".  Current project planning puts this work beyond mainnet.  It is one of the biggest existing risks for the actors project going into mainnet.

We don't seem to be tracking this in any other issues so let's keep this as the designing for protocol upgrades issue.

**Comment by nicola** [comment] 2020-07-20 15:17
Understood. This is indeed a risk, since any parameter or function change, may result into either a "nasty if condition" or a backward compatibility analysis (and for some of parameters it won't lead to a good result).

**Comment by anorth** [comment] 2020-07-21 01:27
I'm closing this as a duplicate of #385 and #353 . We're aware of the issues, and they are much broader than parameter changes. Anything that can handle the code we are likely to want to change in an upgrade will probably handle parameters for free.

"Nasty if condition" will probably be a very attractive option for simple parameter changes.

**Closed by anorth** 2020-07-21 01:27 UTC
