### ISSUE TITLE
computeFaultsFromMissingPoSts encounter a sector not existing at all

### ISSUE THREAD

**Issue by cerasusland** [filecoin-project/specs-actors#370] opened 2020-05-12 18:00 UTC
when i check miss post, I got a sector which I am never committed at all, maybe `Bitfield` ops got some error cause it.
![image](https://user-images.githubusercontent.com/57336347/81728631-5be9cc00-94bd-11ea-8e2b-34ca1f0a693c.png)

![image (1)](https://user-images.githubusercontent.com/57336347/81728708-7459e680-94bd-11ea-9146-97ed3707a01f.png)

the sector of 5 I never committed.

**Comment by anorth** [comment] 2020-05-12 23:17
This was caused by the error fixed in https://github.com/filecoin-project/go-bitfield/pull/4.

Closed by #369

**Closed by anorth** 2020-05-12 23:17 UTC
