### ISSUE TITLE
Miner: Remove references to variable seal proof types

### ISSUE THREAD

**Issue by wadeAlexC** [filecoin-project/specs-actors#903] opened 2020-08-05 19:28 UTC
At some point in the past, Miners could commit sectors with multiple different seal proof types. Given that this is no longer the case, artifacts of this logic should be removed from the codebase:

* `SectorPreCommitInfo.SealProof`: https://github.com/filecoin-project/specs-actors/blob/9d42fb163883f31325b08752c9f4e85d0b3ef22f/actors/builtin/miner/miner_state.go#L106-L108

* `SectorOnChainInfo.SealProof`: https://github.com/filecoin-project/specs-actors/blob/9d42fb163883f31325b08752c9f4e85d0b3ef22f/actors/builtin/miner/miner_state.go#L130-L133

* `SubmitWindowedPoSt`: https://github.com/filecoin-project/specs-actors/blob/9d42fb163883f31325b08752c9f4e85d0b3ef22f/actors/builtin/miner/miner_actor.go#L244-L246

* `PreCommitSector`: https://github.com/filecoin-project/specs-actors/blob/9d42fb163883f31325b08752c9f4e85d0b3ef22f/actors/builtin/miner/miner_actor.go#L387-L389

* `PreCommitSector`: https://github.com/filecoin-project/specs-actors/blob/9d42fb163883f31325b08752c9f4e85d0b3ef22f/actors/builtin/miner/miner_actor.go#L436-L438

* `validateReplaceSector`: https://github.com/filecoin-project/specs-actors/blob/9d42fb163883f31325b08752c9f4e85d0b3ef22f/actors/builtin/miner/miner_actor.go#L1685-L1688

**Comment by ZenGround0** [comment] 2020-08-05 20:13
I'm not sure we want to stop doing this.  My understanding is that we expect future upgrades to introduce new seal proof types.  The code is future proofed to easily support this.  

If I'm mistaken about our current proof upgrade strategy than I agree we should make the suggested changes.

**Comment by wadeAlexC** [comment] 2020-08-05 20:31
The Miner actor doesn't support adding a new seal proof type, though - so this would require a change to the Miner actor code anyway.

**Comment by anorth** [comment] 2020-08-06 02:06
It would require a change to code but, crucially, not a giant migration of millions of sector infos in the state tree. The kind of change that would see this happen is if we found a bug in PoRep or PoSt that required the proof output to change, but was semantically the same kind of proof (same other implied parameters like window post partition size, etc).

Duplicate of #506.

**Closed by anorth** 2020-08-06 02:06 UTC
