### ISSUE TITLE
Integer division in getEffectiveNetworkTime

### ISSUE THREAD

**Issue by zixuanzh** [filecoin-project/specs-actors#329] opened 2020-04-27 16:37 UTC
Existing code does an inverse mapping of realizedCumsum to effectiveNetworkTime but the integer math is always returning zero unless the daily power exceeds the baseline. This is not the intention and we should introduce a notion of precision here. If baseline is 100PiB on the first day and only 50PiB shows up, network time advances by half a day.

**Comment by zixuanzh** [comment] 2020-04-27 16:37
this is related to #317

**Comment by anorth** [comment] 2020-07-02 04:09
Duplicate of #317, merging into that.

**Closed by anorth** 2020-07-02 04:09 UTC
Labels: P1, bug
