### ISSUE TITLE
FaultDeclare failing sectors rawBytePower would be repeatedly deducted

### ISSUE THREAD

**Issue by cerasusland** [filecoin-project/specs-actors#371] opened 2020-05-12 18:06 UTC
as I test the fault set things, i found those failing sectors would be repeatedly calculated, so after several periods my rawBytePower will lost under zero, this is cannot be accepted, so i cannot continue my window period. is this normal designed or a bug?

![image (2)](https://user-images.githubusercontent.com/57336347/81729008-e4686c80-94bd-11ea-9f0d-74b162919cf5.png)

maybe here should add some tags to indicate the deadlines were handled already.

https://github.com/filecoin-project/specs-actors/blob/c97ffb29627b983ed0b66e8cb7f88c65b0370cbd/actors/builtin/miner/miner_actor.go#L1095

**Comment by whyrusleeping** [comment] 2020-05-12 18:09
@anorth thoughts here?

**Comment by anorth** [comment] 2020-05-13 00:05
If faults have been declared, they should not be "detected" as new faults at the proving period end, so power should not change. Just below the linked code snippet is:

```
				// Record newly-faulty sectors.
				newFaults, err := bitfield.SubtractBitField(partitionSectors, st.Faults)
```

which excludes existing faults. Since that uses bitfield subtract, it's possible that it was buggy for the cause fixed in https://github.com/filecoin-project/go-bitfield/pull/4

It *is* expected that at the end of every proving period a penalty is paid for all continuing faults. This involves a fee, but no change to power.

**Comment by anorth** [comment] 2020-05-13 00:06
@cerasusland please let me know if this continues after v0.5. Meanwhile we will continue to expand unit test coverage to attempt to exercise scenarios like this.

**Closed** 2020-05-14 16:45 UTC
Labels: P1 - must have
