### ISSUE TITLE
SectorOnChainInfo Expiration field is not kept consistent with actual sector expiration

### ISSUE THREAD

**Issue by frrist** [filecoin-project/specs-actors#763] opened 2020-07-22 20:52 UTC
When a sector is upgrade from a committed-capacity sector to deal-containing sector it gets scheduled for expiration at the end of its next deadline. However the expiration feild in the sectors `SecotOnChainInfo` struct is not updated to reflect the new expiration value. This complicates tracking when sectors expire as the `Expiration` feild can not be depend on 100% of the time.

 The ask here is to consistently update this value when scheduling/rescheduling sector expiration. cc @Stebalien

**Comment by anorth** [comment] 2020-07-23 01:30
This is by design, maintaining the original intent and avoiding unnecessary writes to sector info.

Note that the `Expiration` does not correspond to the precise epoch that the expiration will be processed. It will be processed at the end of the deadline following that expiration. We (the miner nor chain) cannot know this epoch at the time that the sector is pre-committed and this expiration specified.

Consider it as a desired, or target, expiration. The sector is actually expired when it's marked `Terminated` in its partition.

**Comment by Stebalien** [comment] 2020-07-24 13:18
The concern here was that this makes it harder to tell if a termination was "on time" or "early". It's possible, just a bit gnarly.

**Closed** 2020-08-05 03:07 UTC
Labels: discussion, enhancement, wontfix
