### ISSUE TITLE
Assess replacing SectorStorageWeightDesc by Power

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/specs-actors#466] opened 2020-06-11 17:21 UTC
builtin/power_actor.go has the following TODO decorating four method params:
`// TODO: replace with power if it can be computed by miner` in reference to the params containing the type `[]SectorStorageWeightDesc`.  The methods are `OnSectorTerminate`, `OnFaultBegin`, `OnFaultEnd`, and `OnSectorModifyWeightDesc`.

From the TODO it is ambiguous if this is possible or the right thing to do.  Needs further investigation

**Comment by ZenGround0** [comment] 2020-06-11 20:24
Potential duplicate of #419

**Comment by anorth** [comment] 2020-06-12 06:05
Duplicate of #419

**Closed by anorth** 2020-06-12 06:05 UTC
Labels: information-requested
